repos:
- repo: https://github.com/stackrox/kube-linter
  rev: 0.6.0
  hooks:
  - id: kube-linter
    args: ["lint", "kubernetes"]
- repo: https://github.com/golangci/golangci-lint
  rev: v1.64.7
  hooks:
    - id: golangci-lint
      args: ["--exclude-dirs", "tests"]
