services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=postgres://postgres:postgres@db:5432/rssagg?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rssagg
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
