apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-api
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: api
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: api
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PORT
          value: {{ quote .Values.api.api.env.port }}
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: {{ include "chart.fullname" . }}-db-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ include "chart.fullname" . }}-db-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: {{ include "chart.fullname" . }}-db-secret
        - name: DB_URL
          value: {{ quote .Values.api.api.env.dbUrl }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.api.api.image.repository }}:{{ .Values.api.api.image.tag | default
          .Chart.AppVersion }}
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {{- toYaml .Values.api.api.resources | nindent 10 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-api-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  selector:
    app: api
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.apiService.ports | toYaml | nindent 2 }}
