apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-db
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: db
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: db
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: {{ include "chart.fullname" . }}-db-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ include "chart.fullname" . }}-db-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: {{ include "chart.fullname" . }}-db-secret
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.db.db.image.repository }}:{{ .Values.db.db.image.tag | default
          .Chart.AppVersion }}
        name: db
        ports:
        - containerPort: 5432
        resources: {{- toYaml .Values.db.db.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: {{ include "chart.fullname" . }}-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-db-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbService.type }}
  selector:
    app: db
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.dbService.ports | toYaml | nindent 2 }}
