apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chart.fullname" . }}-db-pv
  labels:
    type: local
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/db
  persistentVolumeReclaimPolicy: Retain
