apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-db-secret
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ required "dbSecret.postgresDb is required" .Values.dbSecret.postgresDb
    | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "dbSecret.postgresPassword is required" .Values.dbSecret.postgresPassword
    | b64enc | quote }}
  POSTGRES_USER: {{ required "dbSecret.postgresUser is required" .Values.dbSecret.postgresUser
    | b64enc | quote }}
type: Opaque
