{
 "title": "API Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success vs Failed Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('minute', timestamp) AS time_bucket, \n    COUNT(CASE WHEN status BETWEEN '200' AND '299' THEN 1 END) AS success_count,\n    COUNT(CASE WHEN status >= '400' THEN 1 END) AS failure_count\nFROM logs\nGROUP BY time_bucket\nORDER BY time_bucket;\n"
    }
   ]
  },
  {
   "title": "Request Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('minute', timestamp) AS time_bucket, \n    COUNT(*) AS request_count\nFROM logs\nGROUP BY time_bucket\nORDER BY time_bucket;\n"
    }
   ]
  },
  {
   "title": "Avg Request Duration (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    avg(duration_ms)\nFROM logs\n"
    }
   ]
  },
  {
   "title": "95th Percentile Duration (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "rawSql": "SELECT round(PERCENTILE_CONT(0.95) \n    WITHIN GROUP (ORDER BY duration_ms)::bigint, 4) AS p95\nFROM logs;\n"
    }
   ]
  },
  {
   "title": "Slowest Endpoints",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n    url, \n    AVG(duration_ms) AS avg_duration_ms,\n    COUNT(*) AS request_count\nFROM logs\nWHERE url not like '/swagger%' and url not like '/favicon%'\nGROUP BY url\nORDER BY avg_duration_ms DESC"
    }
   ]
  },
  {
   "title": "Response Status %",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n    status, \n    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER () AS count\nFROM logs\nGROUP BY status\nORDER BY count DESC;\n"
    }
   ]
  },
  {
   "title": "HTTP Methods %",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    method AS \"label\", \n    COUNT(method) * 100.0 / SUM(COUNT(method)) OVER () AS \"percentage\"\nFROM logs\nGROUP BY method\nORDER BY \"percentage\" DESC;\n"
    }
   ]
  },
  {
   "title": "Response (ms) Distribution %",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH cte AS (\n    SELECT \n        FLOOR(duration_ms / 10) * 10 AS duration_bucket, \n        COUNT(*) AS request_count,\n        CASE\n            WHEN FLOOR(duration_ms / 10) * 10 = 0 THEN '0-9ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 10 THEN '10-19ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 20 THEN '20-29ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 30 THEN '30-39ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 40 THEN '40-49ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 50 THEN '50-59ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 60 THEN '60-69ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 70 THEN '70-79ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 80 THEN '80-89ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 90 THEN '90-99ms'\n            WHEN FLOOR(duration_ms / 10) * 10 = 100 THEN '100ms'\n            ELSE 'Other' \n        END AS bucket_label\n    FROM logs\n    WHERE duration_ms <= 100\n    GROUP BY duration_bucket\n)\nSELECT \n    bucket_label, \n    -- request_count, \n    request_count * 100.0 / SUM(request_count) OVER () AS request_count\nFROM cte\nORDER BY duration_bucket;\n"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \n    caller_user_id, \n    COUNT(*) AS request_count\nFROM logs\nGROUP BY caller_user_id\nORDER BY request_count DESC\n"
    }
   ]
  }
 ]
}