basePath: /v1
host: localhost
info:
  contact:
    name: Ivan
    url: https://github.com/divakaivan
  description: This is a sample server for RSS Aggregator.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: RSS Aggregator API
  version: "1.0"
paths: {}
swagger: "2.0"
