name: Run Unit Tests & Lint

on:
  push:
    branches: [ "main", "work" ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Test
        run: go test ./tests -test.v

      - name: Lint Kubernetes YAML
        uses: stackrox/kube-linter-action@v1.0.6
        with:
          directory: kubernetes
          config: kubernetes/linter-config.yaml
